-- Выполнять только в новой пустой учебной базе от имени её владельца.
CREATE TABLE public.categories (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_id_positive CHECK (id > 0),
  CONSTRAINT categories_name_key UNIQUE (name),
  CONSTRAINT categories_name_valid CHECK (
    char_length(name) BETWEEN 1 AND 100 AND name = btrim(name)
  )
);

CREATE TABLE public.tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  completed boolean NOT NULL DEFAULT false,
  priority text NOT NULL,
  category_id integer NOT NULL,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_id_positive CHECK (id > 0),
  CONSTRAINT tasks_title_valid CHECK (
    char_length(title) BETWEEN 1 AND 100 AND title = btrim(title)
  ),
  CONSTRAINT tasks_priority_valid CHECK (priority IN ('low', 'medium', 'high')),
  CONSTRAINT tasks_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories(id) ON DELETE RESTRICT
);

CREATE INDEX tasks_category_id_idx ON public.tasks(category_id);
